# scripts/summary_sections/_make_stubs.py
from pathlib import Path
TEMPLATE = """# autogenerated stub; replace with real implementation
def append(md, ctx, **kwargs):
    md.append("\\n### {title}")
    md.append("_(pending)_")
"""
sections = [
    "cross_origin_correlations","lead_lag","volatility_regimes","nowcast_attention",
    "trigger_likelihood_v0","ensemble_v0_4","dynamic_vs_static_thresholds",
    "volatility_aware_thresholds","trigger_explainability","trigger_history",
    "label_feedback","rolling_accuracy_snapshot","accuracy_by_model_version",
    "training_data_snapshot","retrain_summary","latest_training_metadata",
    "calibration","per_origin_thresholds","drift_aware_inference","drift_check",
    "live_backtest","burst_detection","source_precision_recall",
]
base = Path(__file__).parent
for name in sections:
    p = base / f"{name}.py"
    if not p.exists():
        p.write_text(TEMPLATE.format(title=name.replace("_"," ").title()), encoding="utf-8")
        print(f"created stub: {p}")
    else:
        print(f"exists: {p}")
print("done.")